[package]
name = "rust_graphs"
version = "0.1.0"
authors = ["Or Golan <golanor@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand= "^0.8.3"
nalgebra = "0.30.1"
num-traits = "0.2.14"
